language: python
python:
  - "3.6"

# The important part is to install pytest, pytest-cov that allows us to generate the coverage report on the Travis-CI server. 
# We also need to install coveralls that can submit the the report to the Coveralls.io site.  
# In the script part we need to run pytest with the --cov flag. We don't need to give a parameter to that flag, but then we might 
# get reports on code that is not relevant to our application. It is better to pass the directory name of our module to it (--cov=directory/) # so the coverage report will be restricted to code in that directory. We need to tell Travis-CI to run the coveralls command after the test 
# ran successfully. 

before_script:
  - pip install -U pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install pylint
script:
  - pytest --cov=UnitTests/
  - pylint ./*py
after_success:
- coveralls 
